services:
  - type: web
    name: finsight-app
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_md
      python training/train.py

    startCommand: "gunicorn 'app:create_app()'"
